version: '3'
volumes: 
    s3_data:
    mongo_data:
services:
    minio:
        image: minio/minio
        volumes:
            - s3_data:/data
        ports:
            - 9000:9000
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: server /data
        restart: always
    createbucket:
        image: minio/mc
        depends_on:
            - minio
        entrypoint: |
            /bin/sh -c ' 
            for i in $$( seq 1 5 );do
            /usr/bin/mc config host add form-file-upload http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
            test=$$(/usr/bin/mc ls | grep data);
            if [[ -z $$test ]]; then
                /usr/bin/mc mb form-file-upload/data;
                echo "Waiting for bucket to be created";
                sleep 5;
            else 
                break;
            fi; 
            done;
            if [[ -z $$test ]]; then exit -1; else exit 0; fi 
            '
    mongo:
        image: mongo
        volumes:
            - mongo_data:/data/db:Z
        ports:
            - 27017:27017
    form-file-upload-service:
        image: daxnet/form-file-upload
        depends_on: 
            - minio
            - mongo
        ports:
            - 8088:80
        environment: 
            - s3__endpoint=http://minio:9000
            - s3__accessKey=AKIAIOSFODNN7EXAMPLE
            - s3__secretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - mongo__connectionString=mongodb://mongo:27017
            - mongo__database=form-file-upload
