apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-form-file-upload-service
  name: {{ .Release.Name }}-form-file-upload-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: {{ .Release.Name }}-form-file-upload-service
status:
  loadBalancer: {}
