apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Release.Name }}-form-file-upload-mongo
  name: {{ .Release.Name }}-form-file-upload-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-form-file-upload-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Release.Name }}-form-file-upload-mongo
    spec:
      containers:
      - image: mongo:3-xenial
        imagePullPolicy: ""
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-form-file-upload-mongo-data
status: {}
